apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: keduit
spec:
  storageClassName: class1
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
